site_name: FT Docs
repo_url: https://github.com/FEITENG-0828/readthedocs_tutorial

nav:
  - Home: index.md
  - About: about.md

theme:
  name: readthedocs
  locale: zh_CN
  # logo: ./docs/img/FeitengGallifreyanLogo.jpg

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
